spring.application.name=enotes

spring.datasource.url=jdbc:mysql://localhost:3306/enotes_test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=user
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none

file.upload.path=notes/

# File or attachment size configuration
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# Email send configuration with MailSender
#email.send.from=${EMAIL_SENDER_ADDRESS}
#spring.mail.host=${SMTP_HOST}
#spring.mail.username=${SMTP_USERNAME}
#spring.mail.password=${SMTP_PASSWORD}
#spring.mail.port=${SMTP_PORT}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Email send configuration with Mailpit
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

email.send.from=no-reply@firstnotes.com
